data:
  cache_dir: data/hf
  split_spec: train[:500]   
  max_patients: 30          
  image_size: 320
  num_workers: 2
  split_file: data/splits.json

train:
  epochs: 4                
  batch_size: 16            
  amp: true
  lr: 3e-4
  weight_decay: 1e-4
  grad_clip: 1.0
