seed: 42

data:
  data:
  cache_dir: data/hf
  split_spec: train
  max_patients: 50
            
  image_size: 320
  num_workers: 2
  split_file: data/splits.json  # created by scripts/make_splits.py

train:
  epochs: 6
  batch_size: 32
  lr: 3.0e-4
  weight_decay: 1.0e-4
  cosine_lr: true
  grad_clip: 1.0
  amp: true
  save_every: 1

model:
  embed_dim: 256
  image_encoder: resnet18
  text_encoder: distilbert-base-uncased
  temperature_init: 0.07

paths:
  results_dir: results
